### ISSUE TITLE
Melhoria: Campo "email" não tem validação de padrão

### ISSUE THREAD

**Issue by alexmnzs** [juscilan/com.juscilan#3]
**Cenário atual:** Campo "email" do formulário de contato não possui validação de padrão, permitindo dados de email inválido, o que ocasiona em falha ao enviar o formulário.

**Cenário desejado:** Validar o preenchimento do campo "email" antes de confirmar o envio do formulário, caso esteja errado, deve exibir mensagem via label para o usuário, indicando que o email informado é inválido.

**Comment by juscilan** [comment]
Done.
